# Generated by Django 2.1 on 2021-02-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterestapp', '0002_auto_20210207_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedImagesToBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageID', models.IntegerField()),
                ('boardID', models.IntegerField()),
            ],
        ),
    ]
